### ISSUE TITLE
Error while trying out steps in the documentation

### ISSUE THREAD

**Issue by kamath-prasad** [WebPlatformForEmbedded/Lightning-node#1]
I get the below error when I tried out https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/nodejs

```
C02V64NTHTD6:Lightning-test i336605$ npm i https://github.com/WebPlatformForEmbedded/Lightning-node.git --save

> canvas@2.3.1 install /Users/kamath/code/timepass/Lightning-test/node_modules/canvas
> node-gyp rebuild

Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
gyp: Call to 'pkg-config cairo --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.12.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kamath/code/timepass/Lightning-test/node_modules/canvas
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN lightning-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kamath/.npm/_logs/2019-03-22T01_53_41_604Z-debug.log
```

Can you please guide me on how to try out a sample code ?

My machine configuration : 

```
Node version : v11.12.0
npm version : 6.7.0
MacOS MoJave Version 10.14.3
```

**Comment by dimaj** [comment]
just got this resolved by running:
```
brew install pkg-config cairo libpng jpeg giflib
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig
```
and by downgrading node to v10: 
```
Node version : v10.15.3
npm version : 6.4.1
```

**Comment by jbstocker** [comment]
> just got this resolved by running:
> 
> ```
> brew install pkg-config cairo libpng jpeg giflib
> export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig
> ```
> 
> and by downgrading node to v10:
> 
> ```
> Node version : v10.15.3
> npm version : 6.4.1
> ```

This didn't fix the error for me

**Comment by jbstocker** [comment]
Fixed by installing following:
https://github.com/Automattic/node-canvas
https://github.com/WebPlatformForEmbedded/node-wpe-webgl

Need to find the brew instructions for each individually.

**Comment by shiv1m** [comment]
Facing the same issue. Not yet fixed for me. Any clues?
