### ISSUE TITLE
Not able to run sample

### ISSUE THREAD

**Issue by dimaj** [WebPlatformForEmbedded/Lightning-node#2]
Trying to follow 'Getting Stated' for NodeJS (https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/nodejs)

ran the following: 
```
$ mkdir my_lightning
$ cd my_lightning
$ npm init # hit 'enter' through all the prompts
$npm i https://github.com/WebPlatformForEmbedded/Lightning-node.git --save
$ cat <<EOF > index.mjs
import lng from "wpe-lightning-node";

class MyApp extends lng.Application {
    static _template() {
        return {
            Text: {text: {text: "hello world"}}
        }
    }
}

const options = {stage: {w: 900, h: 900, clearColor: 0xFF000000}};
options.stage.window = {title: "Border example", fullscreen: false};
const app = new MyApp(options);
EOF
$ node --experimental-modules index.mjs
```
The output was: 
```
(node:77107) ExperimentalWarning: The ESM module loader is experimental.
{ Error: Cannot find module './build/Release/gles2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/djerus200/_work/ghe/Lightning/my_lightning/node_modules/wpe-webgl/gles2.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) code: 'MODULE_NOT_FOUND' }
```
my environment is as follows:
```
Node: v10.15.3
Npm: 6.4.1
OS: macOS Mojave 10.14.4
```

**Comment by dimaj** [comment]
got it to work (osx):
```
brew install pkg-config cairo libpng jpeg giflib libffi glew glfw3
mkdir test
cd test
npm init esm -y
```
copied over the sample code and launched it via provided `node` command.

please update the documentation on how to get this sample to work.

Thank you.
